version: '3.8'

services:
    mongodb:
        image: mongo:latest
        container_name: mongo
        restart: always
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongo
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - mongo-data:/data/db

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_BASICAUTH_USERNAME: mongo
            ME_CONFIG_BASICAUTH_PASSWORD: password

volumes:
    mongo-data:
